### ISSUE TITLE
PHPStorm Components import marked as unused

### ISSUE THREAD

**Issue by abstractFlo** [tomblachut/svelte-intellij#159]
The current version marks some imports as unused like the router-view form @bjornlu/svelte-router

This is a problem, well the reformat code with optimized import removed this line.

Is there any solution to solve this problem?

![image](https://user-images.githubusercontent.com/4614586/95024743-616ecb00-0685-11eb-8c2f-bf5261b22c11.png)

Update the import with an alias, remove the warning

![image](https://user-images.githubusercontent.com/4614586/95024769-8cf1b580-0685-11eb-9edf-74ba662a8c25.png)

**Comment by tomblachut** [comment]
Current version has bugs around imports, there is no real workaround unfortunately - you could disable import optimisation during reformat for now.

**Comment by abstractFlo** [comment]
Aliasing the unresolved import is a good workaround too, phpstorm can now see the use for the import and it's fine. Not perfectly but fine :)

**Comment by tomblachut** [comment]
Should work in 0.14. Please reach out otherwise

**Comment by abstractFlo** [comment]
Works like a charm <3 thank you
